# Credentials for ETO API
<%= ENV['RAILS_ENV'] %>:
  <%= ENV['ETO_API_SITE1'] %>:
    email: <%= ENV['ETO_API_USER1'] %>
    password: <%= ENV['ETO_API_PASS1'] %>
    enterprise: <%= ENV['ETO_API_ENTERPRISE1'] %>
    data_source_id: <%= ENV['ETO_API_DATA_SOURCE1'] %>

  <%= ENV['ETO_API_SITE2'] %>:
    email: <%= ENV['ETO_API_USER2'] %>
    password: <%= ENV['ETO_API_PASS2'] %>
    enterprise: <%= ENV['ETO_API_ENTERPRISE2'] %>
    data_source_id: <%= ENV['ETO_API_DATA_SOURCE2'] %>