name: Make Service Images

on:
  push:
    branches:
      # Just enable this for your branch as needed
      - tb/mper-importer/185008935

# Branch pushes will cancel any running jobs to the same branch
concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - name: Minio
            image: ghcr.io/greenriver/openpath-minio:1.0
            context: docker/minio
            dockerfile: docker/minio/Dockerfile
            cache_key: minio

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.cache_key }}

      - name: Log in to ghcr.io
        env:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $password | docker login ghcr.io -u $username --password-stdin

      # https://github.com/docker/build-push-action
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          context: ${{ matrix.context }}
          builder: ${{ steps.buildx.outputs.name }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}
          build-args: ${{ matrix.build-args }}
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.cache_key }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.cache_key }},mode=max
